import './style.css';

const state = { files: [], selected: '', content: '', terminal: ['nova@workspace:~$ Ready. Commands run inside the local workspace.'], messages: [{role:'assistant', text:'I can inspect files, create and edit code, delete files, and run commands in this local workspace. What are we building?'}], dirty:false };
const api = async (url, options) => { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; };
const escape = value => value.replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const language = name => name.endsWith('.css') ? 'CSS' : name.endsWith('.md') ? 'MARKDOWN' : name.endsWith('.js') ? 'JAVASCRIPT' : 'HTML';

function tree(items) { return items.map(item => item.type === 'directory' ? `<details open><summary>⌄ <span>▱</span> ${escape(item.name)}</summary>${tree(item.children)}</details>` : `<button class="file ${state.selected === item.path ? 'active' : ''}" data-file="${escape(item.path)}"><i>${item.name.split('.').pop()}</i>${escape(item.name)}</button>`).join(''); }
function lines(value) { return value.split('\n').map((line, index) => `<div><i>${index + 1}</i><span>${escape(line) || ' '}</span></div>`).join(''); }
function preview() { const frame = document.querySelector('#preview'); if (!frame) return; const html = state.files.some(f => f.path === 'index.html') ? state.files : []; const find = (nodes, name) => { for (const n of nodes) { if(n.path === name) return n; if(n.children) { const hit = find(n.children, name); if(hit) return hit; } } };
 Promise.all(['index.html','styles.css'].map(path => api(`/api/file?path=${path}`).then(r=>r.content).catch(()=>''))).then(([markup, css]) => frame.srcdoc = `<style>${css}</style>${markup || '<main style="font-family:sans-serif;padding:3rem">Create index.html to see a preview.</main>'}`); }
function render() { document.querySelector('#app').innerHTML = `<div class="shell">
 <nav class="activity"><strong>⌁</strong><button class="selected" title="Explorer">▱</button><button title="Search">⌕</button><button title="Source control">⑂</button><button title="Extensions">▦</button><span></span><button title="Settings">⚙</button><div class="profile">N</div></nav>
 <aside class="explorer"><header><span>EXPLORER</span><button id="createFile">＋</button></header><div class="workspace-title"><b>⌄</b> NOVA-WORKSPACE <button id="refreshTree">↻</button></div><div class="tree">${tree(state.files)}</div><footer><span class="connected"></span> Local workspace connected</footer></aside>
 <main><header class="top"><div class="crumb">nova-workspace <b>/</b> ${escape(state.selected || 'welcome')}</div><div><button id="save" class="save ${state.dirty ? 'dirty' : ''}">${state.dirty ? '● Save' : '✓ Saved'}</button><button class="icon">•••</button></div></header>
 <section class="code"><div class="tabs"><div class="tab"><span class="file-dot"></span>${escape(state.selected || 'Welcome')} <b>×</b></div><button id="createFile2">＋</button></div><div class="code-meta">${language(state.selected)} <span>UTF-8</span><span>Spaces: 2</span></div><div class="editor"><pre id="gutter">${lines(state.content)}</pre><textarea id="editorInput" spellcheck="false" ${state.selected?'':'disabled'}>${escape(state.content)}</textarea></div></section>
 <aside class="preview"><header><span>LIVE PREVIEW</span><div><button id="reloadPreview">↻</button><button id="popoutPreview">↗</button></div></header><div class="frame"><div class="browser"><i></i><i></i><i></i><b>localhost / artifact</b></div><iframe id="preview" sandbox="allow-scripts"></iframe></div><footer><span class="connected"></span> Auto-refresh on save</footer></aside>
 <section class="bottom"><div class="bottom-tabs"><button class="bottom-tab active" data-panel="agent">✦ AGENT <em>1</em></button><button class="bottom-tab" data-panel="terminal">›_ TERMINAL</button><button class="bottom-tab" data-panel="changes">⑂ CHANGES</button></div><div id="panel"></div></section>
 </main></div>`; bind(); renderPanel('agent'); preview(); }
function renderPanel(panel) { const target = document.querySelector('#panel'); if(panel === 'terminal') { target.innerHTML = `<div class="terminal">${state.terminal.map(l=>`<div>${escape(l)}</div>`).join('')}<form id="terminalForm"><label>nova@workspace:~$</label><input id="command" autocomplete="off" placeholder="Type a command and press Enter" /></form></div>`; document.querySelector('#terminalForm').onsubmit = runCommand; return; }
 if(panel === 'changes') { target.innerHTML = `<div class="changes"><b>WORKSPACE CHANGES</b><p>Files are persisted locally. Save an editor change to update the preview.</p></div>`; return; }
 target.innerHTML = `<div class="messages">${state.messages.map(m=>`<div class="message ${m.role}"><span>${m.role==='assistant'?'N':'You'}</span><p>${escape(m.text)}</p></div>`).join('')}</div><form class="ask" id="ask"><textarea id="request" rows="1" placeholder="Ask Nova to build, inspect, or change anything..."></textarea><button title="Add context" type="button">＋</button><button class="send" title="Send">↗</button></form><small>⌘ ↵ to send <i>Agent can read, write, delete, run & preview</i></small>`; const request = document.querySelector('#request'); document.querySelector('#ask').onsubmit = runAgent; request.onkeydown = e => { if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') document.querySelector('#ask').requestSubmit(); }; }
async function loadTree() { state.files = await api('/api/tree'); }
async function openFile(path) { const data = await api(`/api/file?path=${encodeURIComponent(path)}`); state.selected = path; state.content = data.content; state.dirty = false; render(); }
async function save() { if (!state.selected) return; await api('/api/file', {method:'PUT', headers:{'Content-Type':'application/json'}, body:JSON.stringify({path:state.selected,content:state.content})}); state.dirty = false; render(); }
async function newFile() { const path = prompt('New file path', 'components/new-file.html'); if (!path) return; await api('/api/file', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({path,content:''})}); await loadTree(); await openFile(path); }
async function removeFile(path) { if (!confirm(`Delete ${path}?`)) return; await api(`/api/file?path=${encodeURIComponent(path)}`, {method:'DELETE'}); await loadTree(); state.selected = ''; state.content = ''; render(); }
async function runCommand(e) { e.preventDefault(); const command = document.querySelector('#command').value.trim(); if(!command) return; state.terminal.push(`nova@workspace:~$ ${command}`); try { const r = await api('/api/terminal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command})}); state.terminal.push(r.output || '(command completed)'); } catch(err) { state.terminal.push(`Error: ${err.message}`); } renderPanel('terminal'); }
async function runAgent(e) { e.preventDefault(); const input = document.querySelector('#request'); const request = input.value.trim(); if (!request) return; state.messages.push({role:'user',text:request}); const lower=request.toLowerCase(); try { if (/delete|remove/.test(lower)) { const path = findName(request); if (!path) throw new Error('Name a file to delete.'); await api(`/api/file?path=${encodeURIComponent(path)}`,{method:'DELETE'}); await loadTree(); state.messages.push({role:'assistant',text:`Deleted ${path} from the local workspace.`}); } else if (/create|add.*file/.test(lower)) { const path = request.match(/[\w./-]+\.(html|css|js|md|json|txt)/i)?.[0] || 'untitled.md'; await api('/api/file',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path,content:`# ${path.split('/').pop().replace(/\..+$/,'')}\n`})}); await loadTree(); state.messages.push({role:'assistant',text:`Created ${path} and opened it for you.`}); state.selected=path; state.content=await api(`/api/file?path=${encodeURIComponent(path)}`).then(r=>r.content); } else if (/inspect|read|explain/.test(lower)) { const path=findName(request) || state.selected; const content=await api(`/api/file?path=${encodeURIComponent(path)}`).then(r=>r.content); state.messages.push({role:'assistant',text:`${path} has ${content.split('\n').length} lines and ${content.length} characters. It is loaded and ready to change.`}); } else if (/run|terminal|npm|command/.test(lower)) { state.terminal.push(`nova@workspace:~$ ${request.replace(/^.*?(run|command)\s*/i,'') || 'pwd'}`); state.messages.push({role:'assistant',text:'Opened the Terminal panel. Enter a command to run it in the local workspace.'}); render(); renderPanel('terminal'); return; } else { if (!state.selected) throw new Error('Open a file before asking for an edit.'); state.content += `\n<!-- Nova note: ${request} -->`; await save(); state.messages.push({role:'assistant',text:`Updated ${state.selected} and refreshed the preview. Review the change in the editor.`}); }
 render(); } catch(err) { state.messages.push({role:'assistant',text:`I could not complete that: ${err.message}`}); renderPanel('agent'); } }
function findName(text) { const names = []; const collect=n=>n.forEach(x=>{if(x.type==='file')names.push(x.path);if(x.children)collect(x.children)}); collect(state.files); return names.find(n=>text.toLowerCase().includes(n.toLowerCase())); }
function bind() { document.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>openFile(b.dataset.file)); document.querySelector('#createFile').onclick=newFile; document.querySelector('#createFile2').onclick=newFile; document.querySelector('#refreshTree').onclick=async()=>{await loadTree();render()}; document.querySelector('#save').onclick=save; document.querySelector('#editorInput').oninput=e=>{state.content=e.target.value;state.dirty=true;document.querySelector('#gutter').innerHTML=lines(state.content);}; document.querySelector('#reloadPreview').onclick=preview; document.querySelector('#popoutPreview').onclick=()=>{const frame=document.querySelector('#preview'); const win=window.open(); win.document.write(frame.srcdoc);}; document.querySelectorAll('.bottom-tab').forEach(button=>button.onclick=()=>{document.querySelectorAll('.bottom-tab').forEach(x=>x.classList.remove('active'));button.classList.add('active');renderPanel(button.dataset.panel);}); }
await loadTree(); await openFile('index.html');
